INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('999', '', '', '', '', '');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('2121', '', '', '', '', '');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('2332', '', '', '', '', '');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('9992', '', '', '', '', '');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('21212', '', '', '', '', '');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('99912', '', '', '', '', '');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('260642', 'Natalia', 'Gómez', 'Torres', 'natalia.gomez@example.com', '677901234');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('261155', 'Lucía', 'Torres', 'Pérez', 'lucia.torres@example.com', '656789012');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('265262', 'LUCAS', 'NAVARRO', 'RIVERA', 'lucas.navarro@mail.com', '+34 600112233');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('265831', 'Noelia', 'León', 'Gómez', 'noelia.leon@example.com', '677901236');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('265886', 'carlos alonso', 'pérez', 'martínez', 'calonso@hotmail.com', '+34 611223344');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('265918', 'Noelia', 'Ramírez', 'Soler', 'noeliasoler@mail.com', '+34 622334455');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('265957', 'Daniel', 'Roca', NULL, 'daniel.roca@mail.com', '+34 633445566');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('265962', 'CAMILA', 'VILLANUEVA', NULL, 'camila.villa@mail.com', '+34 644556677');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('265980', 'Raquel', 'Domínguez', 'Llorente', 'raquel.dominguez@mail.com', '+34 655667788');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266008', 'Pilar', 'Sánchez Blasco', NULL, 'pilarsb@mail.com', '+34 666778899');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266052', 'Marcos', 'Herrero Ruiz', NULL, 'mherrero42@mail.com', '+34 677889900');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266062', 'Laura', 'Martínez', 'Gómez', 'laura.martinez@example.com', '612345678');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266063', 'Pablo', 'Rodríguez', 'Sánchez', 'pablo.rodriguez@example.com', '623456789');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266064', 'Carmen', 'López', 'Fernández', 'carmen.lopez@example.com', '634567890');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266065', 'Javier', 'García', 'Moreno', 'javier.garcia@example.com', '645678901');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266069', 'Andrés', 'Ruiz', 'Martínez', 'andres.ruiz@example.com', '667890123');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266070', 'Sara', 'Herrera', 'Jiménez', 'sara.herrera@example.com', '678901234');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266071', 'Álvaro', 'Morales', 'Castro', 'alvaro.morales@example.com', '689012345');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266072', 'Beatriz', 'Vargas', 'Delgado', 'beatriz.vargas@example.com', '690123456');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266073', 'David', 'Navarro', 'Ortega', 'david.navarro@example.com', '601234567');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266074', 'Elena', 'Romero', 'Gil', 'elena.romero@example.com', '611345678');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266075', 'Hugo', 'Ramos', 'Cano', 'hugo.ramos@example.com', '622456789');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266076', 'Paula', 'Medina', 'León', 'paula.medina@example.com', '633567890');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266077', 'Marcos', 'Iglesias', 'Bravo', 'marcos.iglesias@example.com', '644678901');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266078', 'Isabel', 'Domínguez', 'Núñez', 'isabel.dominguez@example.com', '655789012');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266079', 'Tomás', 'Sánchez', 'Rubio', 'tomas.sanchez@example.com', '666890123');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266084', 'Víctor', 'Delgado', 'Ríos', 'victor.delgado@example.com', '688012345');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266086', 'Ana', 'Gil', 'Serrano', 'ana.gil@example.com', '699123456');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266087', 'Francisco', 'Morales', 'Pascual', 'francisco.morales@example.com', '600234567');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266090', 'Nuria', 'León', 'Molina', 'nuria.leon@example.com', '611345679');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266091', 'Óscar', 'Cano', 'Bravo', 'oscar.cano@example.com', '622456780');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266092', 'Silvia', 'Castro', 'Ramos', 'silvia.castro@example.com', '633567891');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266093', 'Alejandro', 'Pérez', 'Romero', 'alejandro.perez@example.com', '644678902');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266098', 'Irene', 'Rubio', 'García', 'irene.rubio@example.com', '655789013');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266099', 'Sergio', 'Ortega', 'Jiménez', 'sergio.ortega@example.com', '666890124');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266100', 'Aitana', 'Núñez', 'López', 'aitana.nunez@example.com', '677901235');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266102', 'Daniel', 'Fernández', 'Herrera', 'daniel.fernandez@example.com', '688012346');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266103', 'Clara', 'Molina', 'Rodríguez', 'clara.molina@example.com', '699123457');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266104', 'Luis', 'Bravo', 'Sánchez', 'luis.bravo@example.com', '600234568');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266105', 'Teresa', 'Serrano', 'Morales', 'teresa.serrano@example.com', '611345670');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266106', 'Iván', 'Ríos', 'León', 'ivan.rios@example.com', '622456781');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266108', 'Marta', 'Pascual', 'Cano', 'marta.pascual@example.com', '633567892');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266109', 'Adrián', 'Gil', 'Vargas', 'adrian.gil@example.com', '644678903');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266110', 'Julia', 'Medina', 'Domínguez', 'julia.medina@example.com', '655789014');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266111', 'Rubén', 'Iglesias', 'Navarro', 'ruben.iglesias@example.com', '666890125');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266114', 'Guillermo', 'López', 'García', 'guillermo.lopez@example.com', '688012347');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266115', 'Patricia', 'Delgado', 'Moreno', 'patricia.delgado@example.com', '699123458');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266116', 'Raúl', 'Vargas', 'Pérez', 'raul.vargas@example.com', '600234569');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266118', 'Sonia', 'Ortega', 'Herrera', 'sonia.ortega@example.com', '611345671');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266119', 'Mateo', 'Torres', 'Ramos', 'mateo.torres@example.com', '622456782');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266120', 'Celia', 'Romero', 'Bravo', 'celia.romero@example.com', '633567893');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266121', 'Joaquín', 'Morales', 'Molina', 'joaquin.morales@example.com', '644678904');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266122', 'Alicia', 'Navarro', 'Sánchez', 'alicia.navarro@example.com', '655789015');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266125', 'Mario', 'Gil', 'Cano', 'mario.gil@example.com', '666890126');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266126', 'Eva', 'Rodríguez', 'León', 'eva.rodriguez@example.com', '677901237');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266127', 'Samantha', 'Pérez', 'Sánchez', 'samdssd@gmail.com', '+34 637276216');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266141', 'Andrés', 'Vidal', 'Ortega', 'andres.vidal@mail.com', '+34 699001122');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266158', 'Tomás', 'Moreno', 'Esteban', 't.moreno@mail.com', '+34 611112233');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266167', 'Irene', 'Rubio', NULL, 'irenerubio@mail.com', '+34 622223344');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266175', 'Antonio', 'Garrido Gómez', NULL, 'antoniogarrido@mail.com', '+34 633334455');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266179', 'CLARA', 'León', 'ALBERT', 'clara.leonalbert@mail.com', '+34 644445566');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266180', '', '', '', '', '');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266181', '', '', '', '', '');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266182', '', '', '', '', '');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266183', '', '', '', '', '');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266184', '', '', '', '', '');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266185', '', '', '', '', '');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266186', '', '', '', '', '');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266187', 'prueba', 'prueba', 'prueba', 'prueba@example.com', '000000000');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266188', 'prueba', 'prueba', 'prueba', 'prueba@example.com', '000000000');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266189', 'prueba', 'prueba', 'prueba', 'prueba@example.com', '000000000');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266190', 'prueba', 'prueba', 'prueba', 'prueba@example.com', '000000000');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266191', 'prueba', 'prueba', 'prueba', 'prueba@example.com', '000000000');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266192', 'prueba', 'prueba', 'prueba', 'prueba@example.com', '000000000');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266193', 'prueba', 'prueba', 'prueba', 'prueba@example.com', '000000000');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266194', 'prueba', 'prueba', 'prueba', 'prueba@example.com', '000000000');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('266195', '', '', '', '', '');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('9991112', '', '', '', '', '');
INSERT INTO clientes (id_cliente, nombre, apellido1, apellido2, email, telefono) VALUES ('1212121212', '', '', '', '', '');
